name: MegaMiner
version: '${project.version}'
main: me.jetby.megaminer.MegaMiner
api-version: '1.16'
load: POSTWORLD
depend:
  - Vault
softdepend:
  - PlaceholderAPI
commands:
  megaminer:
    usage: /megaminer reload