messages:
  reload: "&a&lPlugin has been reload."
  noperm: "&c&lNo permission &7(megaminer.admin)"



Blocks:
  STONE:
    Chance: 100
    Disabled-Worlds:
      - newspawn
    Disabled-Enchantments:
      - silk_touch
    Messages:
      Title: ";&c"
      Actionbar: '&c&l> &fYou broke a block and got &c+%money%'
      Message:
        - ' '
        - ' &c&l⌈'
        - ' &c| &fBalance replenished by &c$%money%'
        - ' &c| &fBecause you broke the block.'
        - ' &c&l⌊'
        - ' '
    Commands:
      - give %player% gold_ingot
    Money:
      Min: 10
      Max: 25

  DIAMOND_ORE:
    Chance: 100
    Money:
      Min: 10
      Max: 25
    Messages:
      Actionbar: '&b&l> &fYou broke a block and got &b+%money%'
      Message:
        - ' '
        - ' &b&l⌈'
        - ' &b| &fBalance replenished by &b$%money%'
        - ' &b| &fBecause you broke the block.'
        - ' &b&l⌊'
        - ' '
    Commands:
      - give %player% diamond


# and more...